name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          # Add your test command here
          echo "Running tests..."

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      - name: Terraform Format
        id: fmt
        run: |
          cd terraform
          terraform fmt -check

      - name: Terraform Init
        id: init
        run: |
          cd terraform
          terraform init

      - name: Package Lambda Function
        id: package-lambda
        run: |
          # Create the zip file directly
          cd src
          zip -r ../lambda_function.zip .
          # Verify the zip file was created
          ls -la ../lambda_function.zip
          # Move to terraform directory
          mv ../lambda_function.zip ../terraform/
          # Verify it's in the right place
          ls -la ../terraform/lambda_function.zip

      - name: Terraform Validate
        id: validate
        run: |
          cd terraform
          terraform validate -no-color
          
      - name: Cleanup Lambda Package
        if: always()
        run: |
          # Remove the zip file after validation
          if [ -f terraform/lambda_function.zip ]; then
            rm terraform/lambda_function.zip
          fi

      - name: Deploy to AWS
        if: github.ref == 'refs/heads/main'
        needs: [package-lambda]  # Ensure package step runs first
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1
        run: |
          # Print current directory and list files for debugging
          echo "Current directory:"
          pwd
          ls -la
          
          # Go to terraform directory
          cd terraform
          
          # List files in terraform directory
          echo "Files in terraform directory:"
          ls -la
          
          # Verify lambda_function.zip exists and has content
          echo "Lambda zip file details:"
          ls -lh lambda_function.zip
          
          # Initialize Terraform
          terraform init
          
          # Apply Terraform configuration
          terraform apply -auto-approvee